#!/usr/bin/env python3
"""Additional HealthBench validation for reward- and advantage-space metrics.

The analysis is intentionally conditional on the observed training trajectory.
It uses the same 500 HealthBench prompt IDs across checkpoints and preserves the
training alignment

    policy checkpoint t-1 -> update t metric -> checkpoint t.

Three questions are evaluated for normalized rewards and reconstructed GRPO
advantages separately:

1. Prompt-paired bootstrap uncertainty of HealthBench differences and of the
   checkpoint-level metric/HealthBench correlations.
2. Metric/HealthBench association after removing a prespecified linear step
   trend, with HAC uncertainty for the observed checkpoint trajectory.
3. Association between the metric from update s+1 (generated by policy s) and
   HealthBench at checkpoint s+3 after adjusting for HealthBench at s and step.

The bootstrap captures HealthBench prompt-composition uncertainty only.  It
does not estimate response-generation, judge, metric-batch, or training-seed
uncertainty.
"""

from __future__ import annotations

import json
import shutil
import zipfile
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, rankdata, spearmanr, t as student_t


ROOT = Path(__file__).resolve().parents[1]
REWARD_RESULTS = ROOT / "results/latest_dense_online_vs_static_actual_training_metrics_20260926"
ADVANTAGE_RESULTS = (
    ROOT / "results/latest_dense_online_vs_static_actual_advantage_metrics_20260927"
)
OUTPUT_ROOT = ROOT / "results/healthbench_additional_validation_20260928"

ONLINE_PROMPTS = REWARD_RESULTS / "online_dense_healthbench_prompt_minmax_scores.csv"
STATIC_PROMPTS = REWARD_RESULTS / "static_matched_healthbench_prompt_minmax_scores.csv"
REWARD_METRICS = REWARD_RESULTS / "actual_training_mad_ptr_ecr_by_step.csv"
ADVANTAGE_METRICS = ADVANTAGE_RESULTS / "actual_training_advantage_metrics_by_step.csv"

BOOTSTRAP_REPLICATES = 5_000
BOOTSTRAP_SEED = 20260928
ONLINE_HAC_LAGS_LEVEL = 3
ONLINE_HAC_LAGS_FUTURE = 2
STATIC_HAC_LAGS = 1


@dataclass(frozen=True)
class Representation:
    key: str
    title: str
    metrics_path: Path
    metrics: tuple[str, str, str]
    labels: tuple[str, str, str]


REPRESENTATIONS = (
    Representation(
        key="normalized_reward",
        title="Normalized reward",
        metrics_path=REWARD_METRICS,
        metrics=("MAD", "PTR", "ECR"),
        labels=("MAD", "PTR", "ECR"),
    ),
    Representation(
        key="advantage",
        title="GRPO advantage",
        metrics_path=ADVANTAGE_METRICS,
        metrics=("advantage_MAD", "advantage_PTR", "reward_ECR"),
        labels=("Advantage MAD", "Advantage PTR", "Reward ECR"),
    ),
)

METHODS = {
    "Online": {
        "metric_method": "Online Rubrics",
        "eval_steps": np.arange(1, 49, dtype=int),
        "future_starts": np.arange(1, 46, dtype=int),
        "color": "#2563eb",
    },
    "Static": {
        "metric_method": "Static R0 matched",
        "eval_steps": np.arange(3, 43, 3, dtype=int),
        "future_starts": np.arange(3, 40, 3, dtype=int),
        "color": "#ea580c",
    },
}


def zscore(values: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    std = float(np.std(values, ddof=1))
    if not np.isfinite(std) or std <= 0:
        raise RuntimeError("cannot standardize a constant or invalid vector")
    return (values - float(np.mean(values))) / std


def residualize(values: np.ndarray, controls: np.ndarray) -> np.ndarray:
    design = np.column_stack([np.ones(len(values)), controls])
    coefficients = np.linalg.lstsq(design, values, rcond=None)[0]
    return values - design @ coefficients


def partial_correlation(
    x: np.ndarray, y: np.ndarray, controls: np.ndarray, rank: bool = False
) -> float:
    if rank:
        x = rankdata(x)
        y = rankdata(y)
        controls = np.column_stack(
            [rankdata(controls[:, index]) for index in range(controls.shape[1])]
        )
    x_residual = residualize(np.asarray(x, dtype=float), controls)
    y_residual = residualize(np.asarray(y, dtype=float), controls)
    return float(pearsonr(x_residual, y_residual).statistic)


def ols_hac(
    y: np.ndarray, predictors: np.ndarray, metric_index: int, max_lags: int
) -> dict[str, float]:
    """OLS with a small-sample-corrected Bartlett/Newey-West covariance."""

    y = np.asarray(y, dtype=float)
    predictors = np.asarray(predictors, dtype=float)
    design = np.column_stack([np.ones(len(y)), predictors])
    n, k = design.shape
    if n <= k:
        raise RuntimeError(f"OLS requires n > k, found n={n}, k={k}")
    xtx_inverse = np.linalg.pinv(design.T @ design)
    coefficients = xtx_inverse @ design.T @ y
    residuals = y - design @ coefficients

    meat = np.zeros((k, k), dtype=float)
    for index in range(n):
        vector = design[index][:, None]
        meat += residuals[index] ** 2 * (vector @ vector.T)
    for lag in range(1, max_lags + 1):
        weight = 1.0 - lag / (max_lags + 1.0)
        lag_sum = np.zeros((k, k), dtype=float)
        for index in range(lag, n):
            current = design[index][:, None]
            previous = design[index - lag][:, None]
            lag_sum += residuals[index] * residuals[index - lag] * (
                current @ previous.T + previous @ current.T
            )
        meat += weight * lag_sum
    covariance = xtx_inverse @ meat @ xtx_inverse
    covariance *= n / (n - k)
    standard_errors = np.sqrt(np.maximum(np.diag(covariance), 0.0))

    coefficient_position = metric_index + 1
    estimate = float(coefficients[coefficient_position])
    standard_error = float(standard_errors[coefficient_position])
    degrees_of_freedom = n - k
    critical = float(student_t.ppf(0.975, degrees_of_freedom))
    statistic = estimate / standard_error if standard_error > 0 else np.nan
    p_value = (
        float(2 * student_t.sf(abs(statistic), degrees_of_freedom))
        if np.isfinite(statistic)
        else np.nan
    )
    return {
        "beta": estimate,
        "se": standard_error,
        "ci_low": estimate - critical * standard_error,
        "ci_high": estimate + critical * standard_error,
        "p_value": p_value,
        "hac_max_lags": max_lags,
        "n": n,
        "df": degrees_of_freedom,
        "residual_acf1": (
            float(pearsonr(residuals[:-1], residuals[1:]).statistic) if n > 3 else np.nan
        ),
    }


def nested_partial_r2(y: np.ndarray, base: np.ndarray, metric: np.ndarray) -> float:
    y = np.asarray(y, dtype=float)
    base_design = np.column_stack([np.ones(len(y)), base])
    extended_design = np.column_stack([base_design, metric])
    base_residual = y - base_design @ np.linalg.lstsq(base_design, y, rcond=None)[0]
    extended_residual = y - extended_design @ np.linalg.lstsq(
        extended_design, y, rcond=None
    )[0]
    base_sse = float(base_residual @ base_residual)
    extended_sse = float(extended_residual @ extended_residual)
    return (base_sse - extended_sse) / base_sse if base_sse > 0 else np.nan


def expanding_rmse(
    y: np.ndarray, base_predictors: np.ndarray, metric: np.ndarray, minimum_train: int
) -> tuple[float, float, float, int]:
    base_errors: list[float] = []
    extended_errors: list[float] = []
    for index in range(minimum_train, len(y)):
        train = np.arange(index)
        base_train = np.column_stack([np.ones(index), base_predictors[train]])
        base_test = np.concatenate([[1.0], np.atleast_1d(base_predictors[index])])
        base_fit = np.linalg.lstsq(base_train, y[train], rcond=None)[0]
        base_errors.append(float(y[index] - base_test @ base_fit))

        extended_train = np.column_stack([base_train, metric[train]])
        extended_test = np.concatenate([base_test, [metric[index]]])
        extended_fit = np.linalg.lstsq(extended_train, y[train], rcond=None)[0]
        extended_errors.append(float(y[index] - extended_test @ extended_fit))
    base_rmse = float(np.sqrt(np.mean(np.square(base_errors))))
    extended_rmse = float(np.sqrt(np.mean(np.square(extended_errors))))
    improvement = 100.0 * (base_rmse - extended_rmse) / base_rmse
    return base_rmse, extended_rmse, improvement, len(base_errors)


def rowwise_correlation(y_rows: np.ndarray, x: np.ndarray, rank: bool = False) -> np.ndarray:
    x = rankdata(x) if rank else np.asarray(x, dtype=float)
    y_rows = rankdata(y_rows, axis=1) if rank else np.asarray(y_rows, dtype=float)
    x_centered = x - x.mean()
    y_centered = y_rows - y_rows.mean(axis=1, keepdims=True)
    numerator = y_centered @ x_centered
    denominator = np.sqrt(
        np.sum(y_centered**2, axis=1) * float(np.sum(x_centered**2))
    )
    return numerator / denominator


def rowwise_step_partial(
    y_rows: np.ndarray, metric: np.ndarray, steps: np.ndarray, rank: bool = False
) -> np.ndarray:
    if rank:
        y_rows = rankdata(y_rows, axis=1)
        metric = rankdata(metric)
        steps = rankdata(steps)
    controls = np.column_stack([np.ones(len(steps)), steps])
    projection = controls @ np.linalg.pinv(controls.T @ controls) @ controls.T
    residual_maker = np.eye(len(steps)) - projection
    metric_residual = residual_maker @ metric
    y_residual = y_rows @ residual_maker.T
    return rowwise_correlation(y_residual, metric_residual, rank=False)


def bootstrap_standardized_beta(
    y_rows: np.ndarray, predictors: np.ndarray, metric_index: int
) -> np.ndarray:
    standardized_y = (y_rows - y_rows.mean(axis=1, keepdims=True)) / y_rows.std(
        axis=1, ddof=1, keepdims=True
    )
    design = np.column_stack([np.ones(len(predictors)), predictors])
    mapping = np.linalg.pinv(design.T @ design) @ design.T
    coefficients = standardized_y @ mapping.T
    return coefficients[:, metric_index + 1]


def load_prompt_matrix(path: Path) -> tuple[np.ndarray, np.ndarray, list[str]]:
    frame = pd.read_csv(path)
    if frame.duplicated(["global_step", "prompt_id"]).any():
        raise RuntimeError(f"duplicate checkpoint/prompt rows in {path}")
    pivot = frame.pivot(
        index="global_step", columns="prompt_id", values="prompt_minmax_score"
    ).sort_index()
    if pivot.shape[1] != 500 or pivot.isna().any().any():
        raise RuntimeError(f"expected a complete 500-prompt matrix in {path}")
    return (
        pivot.index.to_numpy(dtype=int),
        pivot.to_numpy(dtype=float),
        pivot.columns.astype(str).tolist(),
    )


def load_healthbench() -> dict[str, dict[str, np.ndarray]]:
    online_steps, online_values, online_prompts = load_prompt_matrix(ONLINE_PROMPTS)
    static_steps, static_values, static_prompts = load_prompt_matrix(STATIC_PROMPTS)
    if online_prompts != static_prompts:
        raise RuntimeError("Online and Static HealthBench prompt IDs do not align")
    if online_steps.tolist() != list(range(1, 49)):
        raise RuntimeError("Online HealthBench must cover checkpoints 1 through 48")
    if static_steps.tolist() != list(range(3, 43, 3)):
        raise RuntimeError("Static HealthBench must cover checkpoints 3, 6, ..., 42")

    rng = np.random.default_rng(BOOTSTRAP_SEED)
    counts = rng.multinomial(
        500, np.full(500, 1.0 / 500), size=BOOTSTRAP_REPLICATES
    ).astype(float)
    return {
        "Online": {
            "steps": online_steps,
            "values": online_values,
            "mean": online_values.mean(axis=1),
            "bootstrap": (online_values @ counts.T / 500.0).T,
        },
        "Static": {
            "steps": static_steps,
            "values": static_values,
            "mean": static_values.mean(axis=1),
            "bootstrap": (static_values @ counts.T / 500.0).T,
        },
    }


def checkpoint_uncertainty(
    healthbench: dict[str, dict[str, np.ndarray]]
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    checkpoint_rows: list[dict[str, object]] = []
    interval_rows: list[dict[str, object]] = []
    summary_rows: list[dict[str, object]] = []

    for method, data in healthbench.items():
        steps = data["steps"]
        observed = data["mean"]
        bootstrap = data["bootstrap"]
        checkpoint_low, checkpoint_high = np.quantile(bootstrap, [0.025, 0.975], axis=0)
        for index, step in enumerate(steps):
            checkpoint_rows.append(
                {
                    "method": method,
                    "checkpoint": int(step),
                    "healthbench": observed[index],
                    "prompt_bootstrap_ci_low": checkpoint_low[index],
                    "prompt_bootstrap_ci_high": checkpoint_high[index],
                    "prompt_bootstrap_ci_width": checkpoint_high[index]
                    - checkpoint_low[index],
                }
            )

        horizons = (1, 3) if method == "Online" else (3,)
        step_to_index = {int(step): index for index, step in enumerate(steps)}
        for horizon in horizons:
            starts = [int(step) for step in steps if int(step) + horizon in step_to_index]
            for start in starts:
                start_index = step_to_index[start]
                end_index = step_to_index[start + horizon]
                differences = bootstrap[:, end_index] - bootstrap[:, start_index]
                low, high = np.quantile(differences, [0.025, 0.975])
                interval_rows.append(
                    {
                        "method": method,
                        "horizon": horizon,
                        "start_checkpoint": start,
                        "end_checkpoint": start + horizon,
                        "healthbench_difference": observed[end_index] - observed[start_index],
                        "prompt_bootstrap_ci_low": low,
                        "prompt_bootstrap_ci_high": high,
                        "probability_positive": float(np.mean(differences > 0)),
                        "ci_excludes_zero": bool(low > 0 or high < 0),
                    }
                )

        full_difference = bootstrap[:, -1] - bootstrap[:, 0]
        full_low, full_high = np.quantile(full_difference, [0.025, 0.975])
        primary_horizon = 3
        primary = [
            row
            for row in interval_rows
            if row["method"] == method and row["horizon"] == primary_horizon
        ]
        summary_rows.append(
            {
                "method": method,
                "evaluated_checkpoints": len(steps),
                "median_checkpoint_ci_width": float(
                    np.median(checkpoint_high - checkpoint_low)
                ),
                "full_span_start": int(steps[0]),
                "full_span_end": int(steps[-1]),
                "full_span_difference": observed[-1] - observed[0],
                "full_span_ci_low": full_low,
                "full_span_ci_high": full_high,
                "full_span_probability_positive": float(np.mean(full_difference > 0)),
                "three_step_intervals": len(primary),
                "three_step_median_difference": float(
                    np.median([row["healthbench_difference"] for row in primary])
                ),
                "three_step_median_ci_width": float(
                    np.median(
                        [
                            row["prompt_bootstrap_ci_high"]
                            - row["prompt_bootstrap_ci_low"]
                            for row in primary
                        ]
                    )
                ),
                "three_step_positive_ci_count": sum(
                    row["prompt_bootstrap_ci_low"] > 0 for row in primary
                ),
                "three_step_negative_ci_count": sum(
                    row["prompt_bootstrap_ci_high"] < 0 for row in primary
                ),
                "three_step_crosses_zero_count": sum(
                    row["prompt_bootstrap_ci_low"] <= 0
                    <= row["prompt_bootstrap_ci_high"]
                    for row in primary
                ),
            }
        )
    return (
        pd.DataFrame(checkpoint_rows),
        pd.DataFrame(interval_rows),
        pd.DataFrame(summary_rows),
    )


def metric_series(
    metrics: pd.DataFrame, method: str, metric: str, steps: np.ndarray
) -> np.ndarray:
    method_name = METHODS[method]["metric_method"]
    selected = metrics.loc[metrics["method"] == method_name, ["training_step", metric]]
    lookup = selected.set_index("training_step")[metric]
    missing = [int(step) for step in steps if int(step) not in lookup.index]
    if missing:
        raise RuntimeError(f"missing {method} {metric} steps: {missing}")
    return lookup.loc[steps].to_numpy(dtype=float)


def correlation_bootstrap_results(
    representation: Representation,
    metrics: pd.DataFrame,
    healthbench: dict[str, dict[str, np.ndarray]],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for method, data in healthbench.items():
        for metric, label in zip(
            representation.metrics, representation.labels, strict=True
        ):
            x = metric_series(metrics, method, metric, data["steps"])
            for correlation_name, rank in (("Pearson", False), ("Spearman", True)):
                observed = (
                    float(spearmanr(x, data["mean"]).statistic)
                    if rank
                    else float(pearsonr(x, data["mean"]).statistic)
                )
                samples = rowwise_correlation(data["bootstrap"], x, rank=rank)
                low, high = np.quantile(samples, [0.025, 0.975])
                expected_sign = -1 if "PTR" in label else 1
                rows.append(
                    {
                        "representation": representation.key,
                        "method": method,
                        "metric": label,
                        "correlation": correlation_name,
                        "estimate": observed,
                        "prompt_bootstrap_ci_low": low,
                        "prompt_bootstrap_ci_high": high,
                        "probability_expected_direction": float(
                            np.mean(samples * expected_sign > 0)
                        ),
                        "bootstrap_replicates": BOOTSTRAP_REPLICATES,
                    }
                )
    return pd.DataFrame(rows)


def step_adjusted_results(
    representation: Representation,
    metrics: pd.DataFrame,
    healthbench: dict[str, dict[str, np.ndarray]],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for method, data in healthbench.items():
        steps = data["steps"].astype(float)
        y = data["mean"]
        hac_lags = ONLINE_HAC_LAGS_LEVEL if method == "Online" else STATIC_HAC_LAGS
        for metric, label in zip(
            representation.metrics, representation.labels, strict=True
        ):
            x = metric_series(metrics, method, metric, data["steps"])
            predictors = np.column_stack([zscore(steps), zscore(x)])
            model = ols_hac(zscore(y), predictors, metric_index=1, max_lags=hac_lags)
            partial_pearson = partial_correlation(
                x, y, steps[:, None], rank=False
            )
            partial_spearman = partial_correlation(
                x, y, steps[:, None], rank=True
            )
            bootstrap_partial = rowwise_step_partial(
                data["bootstrap"], x, steps, rank=False
            )
            bootstrap_spearman = rowwise_step_partial(
                data["bootstrap"], x, steps, rank=True
            )
            bootstrap_betas = bootstrap_standardized_beta(
                data["bootstrap"], predictors, metric_index=1
            )
            pearson_low, pearson_high = np.quantile(
                bootstrap_partial, [0.025, 0.975]
            )
            spearman_low, spearman_high = np.quantile(
                bootstrap_spearman, [0.025, 0.975]
            )
            beta_low, beta_high = np.quantile(bootstrap_betas, [0.025, 0.975])

            rolling = (np.nan, np.nan, np.nan, 0)
            if method == "Online":
                rolling = expanding_rmse(
                    y=y,
                    base_predictors=steps[:, None],
                    metric=x,
                    minimum_train=12,
                )
            rows.append(
                {
                    "representation": representation.key,
                    "method": method,
                    "metric": label,
                    "n": len(y),
                    "partial_pearson": partial_pearson,
                    "partial_pearson_prompt_bootstrap_ci_low": pearson_low,
                    "partial_pearson_prompt_bootstrap_ci_high": pearson_high,
                    "partial_spearman": partial_spearman,
                    "partial_spearman_prompt_bootstrap_ci_low": spearman_low,
                    "partial_spearman_prompt_bootstrap_ci_high": spearman_high,
                    "standardized_metric_beta": model["beta"],
                    "hac_ci_low": model["ci_low"],
                    "hac_ci_high": model["ci_high"],
                    "hac_p_value": model["p_value"],
                    "hac_max_lags": model["hac_max_lags"],
                    "metric_beta_prompt_bootstrap_ci_low": beta_low,
                    "metric_beta_prompt_bootstrap_ci_high": beta_high,
                    "partial_r2": nested_partial_r2(
                        zscore(y), zscore(steps)[:, None], zscore(x)
                    ),
                    "base_rolling_rmse": rolling[0],
                    "metric_rolling_rmse": rolling[1],
                    "rolling_rmse_improvement_percent": rolling[2],
                    "rolling_predictions": rolling[3],
                    "residual_acf1": model["residual_acf1"],
                }
            )
    return pd.DataFrame(rows)


def future_bootstrap_statistics(
    bootstrap: np.ndarray,
    start_indices: np.ndarray,
    end_indices: np.ndarray,
    metric: np.ndarray,
    starts: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    beta_samples = np.empty(len(bootstrap), dtype=float)
    partial_samples = np.empty(len(bootstrap), dtype=float)
    metric_z = zscore(metric)
    step_z = zscore(starts.astype(float))
    for index, trajectory in enumerate(bootstrap):
        baseline = trajectory[start_indices]
        outcome = trajectory[end_indices]
        predictors = np.column_stack([zscore(baseline), step_z, metric_z])
        design = np.column_stack([np.ones(len(outcome)), predictors])
        beta_samples[index] = np.linalg.lstsq(
            design, zscore(outcome), rcond=None
        )[0][-1]
        partial_samples[index] = partial_correlation(
            metric, outcome, np.column_stack([baseline, starts]), rank=False
        )
    return beta_samples, partial_samples


def future_improvement_results(
    representation: Representation,
    metrics: pd.DataFrame,
    healthbench: dict[str, dict[str, np.ndarray]],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    result_rows: list[dict[str, object]] = []
    interval_rows: list[dict[str, object]] = []
    for method, data in healthbench.items():
        starts = METHODS[method]["future_starts"]
        step_to_index = {int(step): index for index, step in enumerate(data["steps"])}
        start_indices = np.asarray([step_to_index[int(step)] for step in starts])
        end_indices = np.asarray([step_to_index[int(step + 3)] for step in starts])
        baseline = data["mean"][start_indices]
        outcome = data["mean"][end_indices]
        delta = outcome - baseline
        delta_bootstrap = (
            data["bootstrap"][:, end_indices] - data["bootstrap"][:, start_indices]
        )
        delta_low, delta_high = np.quantile(delta_bootstrap, [0.025, 0.975], axis=0)
        for index, start in enumerate(starts):
            interval_rows.append(
                {
                    "method": method,
                    "start_checkpoint": int(start),
                    "end_checkpoint": int(start + 3),
                    "healthbench_start": baseline[index],
                    "healthbench_end": outcome[index],
                    "healthbench_difference": delta[index],
                    "prompt_bootstrap_ci_low": delta_low[index],
                    "prompt_bootstrap_ci_high": delta_high[index],
                }
            )

        hac_lags = ONLINE_HAC_LAGS_FUTURE if method == "Online" else STATIC_HAC_LAGS
        for metric_name, label in zip(
            representation.metrics, representation.labels, strict=True
        ):
            metric = metric_series(metrics, method, metric_name, starts + 1)
            predictors = np.column_stack(
                [zscore(baseline), zscore(starts.astype(float)), zscore(metric)]
            )
            model = ols_hac(
                zscore(outcome), predictors, metric_index=2, max_lags=hac_lags
            )
            partial = partial_correlation(
                metric,
                outcome,
                np.column_stack([baseline, starts]),
                rank=False,
            )
            beta_samples, partial_samples = future_bootstrap_statistics(
                data["bootstrap"], start_indices, end_indices, metric, starts
            )
            beta_low, beta_high = np.quantile(beta_samples, [0.025, 0.975])
            partial_low, partial_high = np.quantile(partial_samples, [0.025, 0.975])
            rolling = (np.nan, np.nan, np.nan, 0)
            if method == "Online":
                rolling = expanding_rmse(
                    y=outcome,
                    base_predictors=np.column_stack([baseline, starts]),
                    metric=metric,
                    minimum_train=15,
                )
            result_rows.append(
                {
                    "representation": representation.key,
                    "method": method,
                    "metric": label,
                    "n": len(starts),
                    "metric_update_alignment": "s+1",
                    "outcome_checkpoint_alignment": "s+3",
                    "partial_pearson": partial,
                    "partial_pearson_prompt_bootstrap_ci_low": partial_low,
                    "partial_pearson_prompt_bootstrap_ci_high": partial_high,
                    "standardized_metric_beta": model["beta"],
                    "hac_ci_low": model["ci_low"],
                    "hac_ci_high": model["ci_high"],
                    "hac_p_value": model["p_value"],
                    "hac_max_lags": model["hac_max_lags"],
                    "metric_beta_prompt_bootstrap_ci_low": beta_low,
                    "metric_beta_prompt_bootstrap_ci_high": beta_high,
                    "partial_r2": nested_partial_r2(
                        zscore(outcome),
                        np.column_stack(
                            [zscore(baseline), zscore(starts.astype(float))]
                        ),
                        zscore(metric),
                    ),
                    "base_rolling_rmse": rolling[0],
                    "metric_rolling_rmse": rolling[1],
                    "rolling_rmse_improvement_percent": rolling[2],
                    "rolling_predictions": rolling[3],
                    "descriptive_metric_delta_pearson": float(
                        pearsonr(metric, delta).statistic
                    ),
                    "descriptive_metric_delta_spearman": float(
                        spearmanr(metric, delta).statistic
                    ),
                    "residual_acf1": model["residual_acf1"],
                }
            )
    return pd.DataFrame(result_rows), pd.DataFrame(interval_rows).drop_duplicates()


def plot_measurement_uncertainty(
    healthbench: dict[str, dict[str, np.ndarray]],
    checkpoint_ci: pd.DataFrame,
    interval_ci: pd.DataFrame,
    output_paths: list[Path],
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(15.2, 9.2), constrained_layout=True)
    for row, method in enumerate(("Online", "Static")):
        checkpoint = checkpoint_ci.loc[checkpoint_ci["method"] == method]
        axis = axes[row, 0]
        axis.plot(
            checkpoint["checkpoint"],
            checkpoint["healthbench"],
            color=METHODS[method]["color"],
            linewidth=1.8,
            marker="o",
            markersize=3.5,
        )
        axis.fill_between(
            checkpoint["checkpoint"],
            checkpoint["prompt_bootstrap_ci_low"],
            checkpoint["prompt_bootstrap_ci_high"],
            color=METHODS[method]["color"],
            alpha=0.18,
        )
        axis.set_title(f"{method}: checkpoint HealthBench with 95% prompt-bootstrap CI")
        axis.set_xlabel("Checkpoint")
        axis.set_ylabel("HealthBench prompt-minmax mean")
        axis.grid(alpha=0.25)

        intervals = interval_ci.loc[
            (interval_ci["method"] == method) & (interval_ci["horizon"] == 3)
        ]
        axis = axes[row, 1]
        y = intervals["healthbench_difference"].to_numpy()
        lower = intervals["prompt_bootstrap_ci_low"].to_numpy()
        upper = intervals["prompt_bootstrap_ci_high"].to_numpy()
        axis.errorbar(
            intervals["start_checkpoint"],
            y,
            yerr=np.vstack([y - lower, upper - y]),
            fmt="o",
            markersize=4,
            linewidth=1,
            capsize=2,
            color=METHODS[method]["color"],
            alpha=0.85,
        )
        axis.axhline(0, color="#374151", linewidth=1, linestyle="--")
        axis.set_title(f"{method}: paired 3-step HealthBench difference")
        axis.set_xlabel("Start checkpoint s")
        axis.set_ylabel("HealthBench(s+3) - HealthBench(s)")
        axis.grid(alpha=0.25)
    fig.suptitle(
        f"HealthBench measurement uncertainty ({BOOTSTRAP_REPLICATES:,} paired prompt bootstraps)",
        fontsize=15,
    )
    for path in output_paths:
        fig.savefig(path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_step_adjusted(
    representation: Representation,
    metrics: pd.DataFrame,
    healthbench: dict[str, dict[str, np.ndarray]],
    results: pd.DataFrame,
    output: Path,
) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(16.5, 9.3), constrained_layout=True)
    scatter = None
    for row, method in enumerate(("Online", "Static")):
        data = healthbench[method]
        steps = data["steps"].astype(float)
        y_residual = residualize(data["mean"], steps[:, None])
        for column, (metric, label) in enumerate(
            zip(representation.metrics, representation.labels, strict=True)
        ):
            axis = axes[row, column]
            x = metric_series(metrics, method, metric, data["steps"])
            x_residual = residualize(x, steps[:, None])
            scatter = axis.scatter(
                x_residual,
                y_residual,
                c=steps,
                cmap="viridis" if method == "Online" else "plasma",
                s=42,
                edgecolor="white",
                linewidth=0.4,
            )
            line_x = np.linspace(x_residual.min(), x_residual.max(), 100)
            slope, intercept = np.polyfit(x_residual, y_residual, 1)
            axis.plot(line_x, intercept + slope * line_x, color="#111827", linewidth=1.2)
            result = results.loc[
                (results["method"] == method) & (results["metric"] == label)
            ].iloc[0]
            axis.set_title(f"{method} — {label}")
            axis.set_xlabel("Metric residual after linear step adjustment")
            axis.set_ylabel("HealthBench residual after linear step adjustment")
            axis.grid(alpha=0.22)
            axis.text(
                0.03,
                0.97,
                (
                    f"partial r={result['partial_pearson']:+.3f}\n"
                    f"beta={result['standardized_metric_beta']:+.3f} "
                    f"[{result['hac_ci_low']:+.3f}, {result['hac_ci_high']:+.3f}]\n"
                    f"HAC p={result['hac_p_value']:.3f}"
                ),
                transform=axis.transAxes,
                va="top",
                fontsize=9,
                bbox={"facecolor": "white", "alpha": 0.82, "edgecolor": "#d1d5db"},
            )
        if scatter is not None:
            fig.colorbar(scatter, ax=axes[row, :], label="Checkpoint step", shrink=0.86)
    fig.suptitle(
        f"{representation.title}: metric–HealthBench relationship after linear step adjustment",
        fontsize=15,
    )
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_future_improvement(
    representation: Representation,
    metrics: pd.DataFrame,
    healthbench: dict[str, dict[str, np.ndarray]],
    results: pd.DataFrame,
    interval_ci: pd.DataFrame,
    output: Path,
) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(16.5, 9.3), constrained_layout=True)
    scatter = None
    for row, method in enumerate(("Online", "Static")):
        data = healthbench[method]
        starts = METHODS[method]["future_starts"]
        step_to_index = {int(step): index for index, step in enumerate(data["steps"])}
        start_indices = np.asarray([step_to_index[int(step)] for step in starts])
        end_indices = np.asarray([step_to_index[int(step + 3)] for step in starts])
        delta = data["mean"][end_indices] - data["mean"][start_indices]
        intervals = interval_ci.loc[interval_ci["method"] == method].set_index(
            "start_checkpoint"
        )
        lower = intervals.loc[starts, "prompt_bootstrap_ci_low"].to_numpy()
        upper = intervals.loc[starts, "prompt_bootstrap_ci_high"].to_numpy()
        for column, (metric, label) in enumerate(
            zip(representation.metrics, representation.labels, strict=True)
        ):
            axis = axes[row, column]
            x = metric_series(metrics, method, metric, starts + 1)
            axis.errorbar(
                x,
                delta,
                yerr=np.vstack([delta - lower, upper - delta]),
                fmt="none",
                ecolor="#9ca3af",
                alpha=0.45,
                linewidth=0.8,
            )
            scatter = axis.scatter(
                x,
                delta,
                c=starts,
                cmap="viridis" if method == "Online" else "plasma",
                s=42,
                edgecolor="white",
                linewidth=0.4,
            )
            line_x = np.linspace(x.min(), x.max(), 100)
            slope, intercept = np.polyfit(x, delta, 1)
            axis.plot(line_x, intercept + slope * line_x, color="#111827", linewidth=1.2)
            axis.axhline(0, color="#6b7280", linewidth=1, linestyle="--")
            result = results.loc[
                (results["method"] == method) & (results["metric"] == label)
            ].iloc[0]
            axis.set_title(f"{method} — {label}")
            axis.set_xlabel(f"{label} at update s+1")
            axis.set_ylabel("HealthBench(s+3) - HealthBench(s)")
            axis.grid(alpha=0.22)
            axis.text(
                0.03,
                0.97,
                (
                    f"adjusted beta={result['standardized_metric_beta']:+.3f}\n"
                    f"HAC 95% CI [{result['hac_ci_low']:+.3f}, "
                    f"{result['hac_ci_high']:+.3f}]\n"
                    f"HAC p={result['hac_p_value']:.3f}"
                ),
                transform=axis.transAxes,
                va="top",
                fontsize=9,
                bbox={"facecolor": "white", "alpha": 0.82, "edgecolor": "#d1d5db"},
            )
        if scatter is not None:
            fig.colorbar(scatter, ax=axes[row, :], label="Start checkpoint s", shrink=0.86)
    fig.suptitle(
        f"{representation.title}: update s+1 metric and 3-step future HealthBench improvement",
        fontsize=15,
    )
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def write_bundle(output: Path) -> None:
    bundle = output / "analysis_tables.zip"
    with zipfile.ZipFile(bundle, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(output.glob("*.csv")):
            archive.write(path, arcname=path.name)
        for path in sorted(output.glob("*.json")):
            archive.write(path, arcname=path.name)


def main() -> None:
    healthbench = load_healthbench()
    checkpoint_ci, interval_ci, uncertainty_summary = checkpoint_uncertainty(healthbench)

    representation_outputs: list[Path] = []
    for representation in REPRESENTATIONS:
        output = OUTPUT_ROOT / representation.key
        output.mkdir(parents=True, exist_ok=True)
        representation_outputs.append(output)
        metrics = pd.read_csv(representation.metrics_path)

        correlation_results = correlation_bootstrap_results(
            representation, metrics, healthbench
        )
        step_results = step_adjusted_results(representation, metrics, healthbench)
        future_results, future_intervals = future_improvement_results(
            representation, metrics, healthbench
        )

        checkpoint_ci.to_csv(output / "healthbench_checkpoint_prompt_bootstrap_ci.csv", index=False)
        interval_ci.to_csv(output / "healthbench_paired_difference_ci.csv", index=False)
        uncertainty_summary.to_csv(output / "healthbench_uncertainty_summary.csv", index=False)
        correlation_results.to_csv(
            output / "metric_healthbench_prompt_bootstrap_correlations.csv", index=False
        )
        step_results.to_csv(output / "step_adjusted_results.csv", index=False)
        future_results.to_csv(output / "future_improvement_results.csv", index=False)
        future_intervals.to_csv(output / "future_improvement_intervals.csv", index=False)

        plot_step_adjusted(
            representation,
            metrics,
            healthbench,
            step_results,
            output / "figure2_step_adjusted_relationships.png",
        )
        plot_future_improvement(
            representation,
            metrics,
            healthbench,
            future_results,
            future_intervals,
            output / "figure3_future_improvement.png",
        )

        summary = {
            "representation": representation.key,
            "created_on": "2026-09-28",
            "bootstrap": {
                "replicates": BOOTSTRAP_REPLICATES,
                "seed": BOOTSTRAP_SEED,
                "resampling_unit": "HealthBench prompt_id paired across all checkpoints",
                "scope": "prompt-composition uncertainty conditional on the observed trajectory",
            },
            "alignment": {
                "current_checkpoint": "policy t-1 -> update t metric -> checkpoint t HealthBench",
                "future_improvement": (
                    "checkpoint s baseline -> update s+1 metric from policy s -> "
                    "checkpoint s+3 HealthBench"
                ),
            },
            "step_model": "standardized HB_t ~ standardized step_t + standardized metric_t",
            "future_model": (
                "standardized HB_(s+3) ~ standardized HB_s + standardized step_s + "
                "standardized metric_(s+1)"
            ),
            "hac_lags": {
                "online_current_level": ONLINE_HAC_LAGS_LEVEL,
                "online_future_h3": ONLINE_HAC_LAGS_FUTURE,
                "static": STATIC_HAC_LAGS,
            },
            "limitations": [
                "single training seed and one observed trajectory",
                "prompt bootstrap excludes generation, judge, metric-batch, and training-seed uncertainty",
                "Static has 14 level observations and 13 future-improvement windows",
                "overlapping Online h=3 windows are handled with HAC but remain observational",
                "no causal interpretation",
            ],
        }
        (output / "analysis_manifest.json").write_text(
            json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        write_bundle(output)

    figure1_paths = [
        output / "figure1_healthbench_measurement_uncertainty.png"
        for output in representation_outputs
    ]
    plot_measurement_uncertainty(
        healthbench, checkpoint_ci, interval_ci, figure1_paths
    )
    for output in representation_outputs:
        # Rebuild the bundle so Figure 1's companion tables and final manifest are included.
        write_bundle(output)

    print(f"wrote additional validation outputs to {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()
